# SETI_Al/config/test_settings_config/ETSI_EN300086_CP50/6_rx_Maximum_Usable_Sensitivity.yaml
#Note Aaron Fans report from 24th Oct 2020
#and Mahruz report 6th Dec 2024
#use
#for MUS 20dB sinad CCITT on
#Frequencies   459.075MHz 498.7MHz  519.2 MHz
#Mus limit  -107dBm for 20dB sinad.   But this is conducted
#ACS limit  60dB with wanted at -95dBm  at ambient and -95 at extreme temps wanted sinad 14dB

frequency:
  - 459.075
  - 498.7
  - 519.2

Bandwidth:
  - NB
  - WB

power:
  levels: [-20, -60, -80, -100, -107,-110, -114, -115, -116, -117, -118, -119, -120, -121, -122, -123, -124, -125]
  #levels: [-114,-120,-125]

ccitt: true   #psophometric_weighting

sinad_min : 10   #less than this stop measuring

radio_voltage: 7.4

temperature: 60

this_test_abr: MUS #ACS  #BI  #  SRI

log_script_prefix: 6_rx_Maximum_Usable_Sensitivity    #7_rx_Adjacent_Channel_Selectivity    #8_rx_blocking_immunity_results    #  9_rx_Spurious_Response_Immunity



#sample_rate: 44100
#no_samples: 16384



#radio_volume:   #position at 9-10AM
#    - 17.0

#sinad_tolerance: 0.25

#Old frequencies:
#  - 452
#  - 460
#  - 485
#  - 520

#frequencies used in the mts
#Frequency	Sensitivity[dB] @ RF Power: -114dBm of MTS2
#	250520001(CP50 3D2)	240430117（CP40)
#451200000 Hz	16.88	21.59
#461200000 Hz	17.47	18.01
#471200000 Hz	17.05	19.31
#481200000 Hz	16.28	20.88
#491200000 Hz	16.78	20.36
#501200000 Hz	15.21	22.19
#511200000 Hz	16.97	22.89
#521200000 Hz	16.63	21.64


#sinad_target:   # these values hard coded in for now
#    high: 20.0
#    mid: 14.0
#    low:  12.0

#power:
#  levels: [-20,-60, -80, -100, -110, -112, -114, -116, -116.5, -117, -117.5, -118, -118.5, -119, -119.5, -120, -120.5, -121, -121.5, -122, -123, -124, -125]

#power:
#  levels: [-20, -114, -118, -120, -122]
